#!/bin/sh

#used by /etc/systemd/system/import_zpool.service

## some general tuning for beegfs
echo 5 > /proc/sys/vm/dirty_background_ratio
echo 20 > /proc/sys/vm/dirty_ratio
echo 50 > /proc/sys/vm/vfs_cache_pressure
echo 262144 > /proc/sys/vm/min_free_kbytes
echo 1 > /proc/sys/vm/zone_reclaim_mode

echo always > /sys/kernel/mm/transparent_hugepage/enabled
echo always > /sys/kernel/mm/transparent_hugepage/defrag

## disable zfs-import-cache, zfs-import-scan, zfs-mount services, do manual import with multipath
zpool import -d /dev/mapper -a
