#!/bin/bash

if [ ! -f hdd_serial ]; then
  lsblk --nodeps -o name,size,serial > hdd_serial
  ./encled >> hdd_serial
fi

## [root@ddn02 ~]# grep 5000cca222f396c5 hdd_serial 
## sdcn    5000cca222f396c5
## sddp    5000cca222f396c5

for enc in `ls /sys/class/enclosure`; do
  for i in $(seq 0 4); do
    for j in $(seq 0 9) A B; do
	 device=$(awk '{print $1,$3,$4}' hdd_serial | grep "$i$j"| grep "$enc" | awk '{print $3}');
	 echo $device
    done | xargs
  done > disk.`echo $enc|tr ":" "_"`
done
