#!/bin/sh
## distribute 57 pools to 9 deamons on both nodes

for dn in `seq 1 9`;do
  mkdir  /etc/beegfs/inst$dn.d
  cp /etc/beegfs/beegfs-storage.conf /etc/beegfs/inst$dn.d/

  sed -i "/sysMgmtdHost/c\sysMgmtdHost = hpc-10ke1.hpcc.usc.edu " /etc/beegfs/inst$dn.d/beegfs-storage.conf
  sed -i "/connStoragePortTCP/c\connStoragePortTCP = 900$dn " /etc/beegfs/inst$dn.d/beegfs-storage.conf
  sed -i "/connStoragePortUDP/c\connStoragePortUDP = 900$dn " /etc/beegfs/inst$dn.d/beegfs-storage.conf
  sed -i "/logStdFile/c\logStdFile =  /var/log/beegfs-storage_$dn.log" /etc/beegfs/inst$dn.d/beegfs-storage.conf
  sed -i "/connInterfacesFile/c\connInterfacesFile = /etc/beegfs/interface_$dn " /etc/beegfs/inst$dn.d/beegfs-storage.conf
  echo ib$dn > /etc/beegfs/interface_$dn
done

if [ $(hostname) == hpc-10ke1.hpcc.usc.edu ];then
declare -i pn=1
while [ $pn -lt 58 ];do
  dn=`echo $(( ($pn-1)/2 % 9 + 1))`
  /opt/beegfs/sbin/beegfs-setup-storage -c /etc/beegfs/inst$dn.d/beegfs-storage.conf -p /data/pool-$pn -s 1$dn -S DDN-1-inst$dn -i $pn
  pn=pn+2
done
fi

if [ $(hostname) == hpc-10ke2.hpcc.usc.edu ];then
declare -i pn=2
while [ $pn -lt 58 ];do
  dn=`echo $(( ($pn-2)/2 % 9 + 1))`
  /opt/beegfs/sbin/beegfs-setup-storage -c /etc/beegfs/inst$dn.d/beegfs-storage.conf -p /data/pool-$pn -s 2$dn -S DDN-2-inst$dn -i $pn
  pn=pn+2
done
fi
